In [1]:
import torch
print(torch.__version__)

2.11.0+cpu


In [2]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"using GPU: {torch.cuda.get_device_name()}")
else:
  print("GPU is not available")

GPU is not available


# Creating a tensor

In [4]:
#using empty -> allocate memory (garbage values which was there at memeory location)
a = torch.empty(2,3)
print(type(a))

<class 'torch.Tensor'>


In [5]:
#using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
#using rand
torch.rand(2,3)

tensor([[0.2656, 0.7151, 0.6131],
        [0.1203, 0.1157, 0.9439]])

In [8]:
torch.rand(2,3)

tensor([[0.4746, 0.7804, 0.0144],
        [0.9903, 0.8116, 0.8163]])

In [9]:
#manual_seed -> reproducibility
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [10]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [11]:
# custom tensors
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [12]:
#other ways
#arrange

print("using arange -> ", torch.arange(0,10,2))

#using linspace
print("using linspaec -> ", torch.linspace(0,10,10))

#using eye
print("using eye -> ", torch.eye(5))

#using full
print("using full -> ", torch.full((3,3),5))

using arange ->  tensor([0, 2, 4, 6, 8])
using linspaec ->  tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye ->  tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full ->  tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


# Tensor Shapes

In [13]:
x = torch.tensor([[1,2,3],[4,5,6]])
print(x, x.shape)

tensor([[1, 2, 3],
        [4, 5, 6]]) torch.Size([2, 3])


In [14]:
torch.empty_like(x)  #same shape

tensor([[139148051021184, 139148051021184,           65536],
        [              1,              48,             128]])

In [16]:
torch.zeros_like(x)


tensor([[0, 0, 0],
        [0, 0, 0]])

In [17]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [26]:
torch.rand_like(x, dtype=torch.float)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

# Data Types

In [21]:
x.dtype

torch.int64

In [22]:
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [23]:
torch.tensor([1,2,3], dtype=torch.float)

tensor([1., 2., 3.])

In [25]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

## 8, 16,32,64 -> int/float, BFloat16, complex64/128, 8-bit unsigned integer, Boolean, Quantized (unsigned) integer

# Mathematical Operations

In [30]:
# scalar Operation
x = torch.rand(2,2)
x

tensor([[0.1784, 0.8238],
        [0.5557, 0.9770]])

In [31]:
print(x + 2)
print(x-2)
print(x * 3)
print(x / 3)
print((x*100)//3)
print(((x*100)//2)%2)
print(x**2)

tensor([[2.1784, 2.8238],
        [2.5557, 2.9770]])
tensor([[-1.8216, -1.1762],
        [-1.4443, -1.0230]])
tensor([[0.5353, 2.4715],
        [1.6672, 2.9311]])
tensor([[0.0595, 0.2746],
        [0.1852, 0.3257]])
tensor([[ 5., 27.],
        [18., 32.]])
tensor([[0., 1.],
        [1., 0.]])
tensor([[0.0318, 0.6787],
        [0.3089, 0.9546]])


## Element Wise Operations

In [32]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.4440, 0.9478, 0.7445],
        [0.4892, 0.2426, 0.7003]])
tensor([[0.5277, 0.2472, 0.7909],
        [0.4235, 0.0169, 0.2209]])


In [33]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**b)

tensor([[0.9717, 1.1950, 1.5354],
        [0.9127, 0.2595, 0.9212]])
tensor([[-0.0837,  0.7007, -0.0464],
        [ 0.0657,  0.2257,  0.4794]])
tensor([[0.2343, 0.2343, 0.5888],
        [0.2072, 0.0041, 0.1547]])
tensor([[ 0.8415,  3.8346,  0.9413],
        [ 1.1552, 14.3533,  3.1705]])
tensor([[0.6515, 0.9868, 0.7919],
        [0.7388, 0.9763, 0.9243]])


In [36]:
c = torch.tensor([-1,0,2,-6])
print(abs(c), torch.abs(c), torch.neg(c))

tensor([1, 0, 2, 6]) tensor([1, 0, 2, 6]) tensor([ 1,  0, -2,  6])


In [39]:
d = torch.tensor([1.9,2.3,1.5,2.7])
torch.round(d), torch.ceil(d), torch.floor(d)

(tensor([2., 2., 2., 3.]), tensor([2., 3., 2., 3.]), tensor([1., 2., 1., 2.]))

In [40]:
#clamp
torch.clamp(d, min=1.5, max=2.5)

tensor([1.9000, 2.3000, 1.5000, 2.5000])

## Reduction Operations

In [41]:
e = torch.randint(size=(2,3), low=0, high=10)
e

tensor([[3, 9, 4],
        [0, 5, 7]])

In [45]:
torch.randint(0,10,(2,3))

tensor([[7, 9, 2],
        [6, 7, 7]])

In [46]:
torch.sum(e)

tensor(28)

In [49]:
print(torch.sum(e, dim=1)) #rows
print(torch.sum(e, dim=0)) #colns

tensor([16, 12])
tensor([ 3, 14, 11])


In [62]:
#mean (only works with float or complex not long)
e = e.to(torch.float32)
print(e)
print(torch.mean(e))


#mean along col
print(torch.mean(e, dim=0))

#mean along row
print(torch.mean(e, dim=1))

#max
print(torch.max(e))

#min
print(torch.min(e))

#prod
print(torch.prod(e))

#std
print(torch.std(e))

#var
print(torch.var(e))


#argmax
print(torch.argmax(e))

#argmin
print(torch.argmin(e))

tensor([[3., 9., 4.],
        [0., 5., 7.]])
tensor(4.6667)
tensor([1.5000, 7.0000, 5.5000])
tensor([5.3333, 4.0000])
tensor(9.)
tensor(0.)
tensor(0.)
tensor(3.1411)
tensor(9.8667)
tensor(1)
tensor(3)


# Matrix Multiplication

In [63]:
f = torch.randint(0,10,(2,3))
g = torch.randint(0,10,(3,2))
print(f)
print(g)

tensor([[8, 3, 6],
        [1, 5, 5]])
tensor([[0, 4],
        [3, 8],
        [8, 3]])


In [64]:
# matrix multiplication

torch.matmul(f,g)

tensor([[57, 74],
        [55, 59]])

In [65]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

torch.dot(vector1, vector2)

tensor(11)

In [68]:
# transpose

print(f)
torch.transpose(f, 0, 1)


tensor([[8, 3, 6],
        [1, 5, 5]])


tensor([[8, 1],
        [3, 5],
        [6, 5]])

In [71]:
# determinant
h = torch.randint(0,10,(3,3),dtype=torch.float32)
h

tensor([[2., 3., 8.],
        [5., 6., 2.],
        [9., 5., 0.]])

In [72]:
torch.det(h)

tensor(-198.)

In [73]:
torch.inverse(h)

tensor([[ 0.0505, -0.2020,  0.2121],
        [-0.0909,  0.3636, -0.1818],
        [ 0.1465, -0.0859,  0.0152]])

## Comparision Operations

In [75]:
i = torch.randint(0,10,(2,3))
j = torch.randint(0,10,(2,3))

print(i)
print(j)

tensor([[7, 2, 5],
        [6, 1, 4]])
tensor([[5, 6, 9],
        [2, 3, 1]])


In [76]:
i>j

tensor([[ True, False, False],
        [ True, False,  True]])

In [77]:
i<j

tensor([[False,  True,  True],
        [False,  True, False]])

In [78]:
i==j

tensor([[False, False, False],
        [False, False, False]])

In [79]:
i!=j

tensor([[True, True, True],
        [True, True, True]])

## Special Functions

In [80]:
k = torch.randint(0,10,(2,3))
k

tensor([[0, 2, 1],
        [2, 7, 9]])

In [84]:
print(torch.log(k))
print(torch.exp(k))
print(torch.sin(k))
print(torch.sigmoid(k))
print(torch.sqrt(k))
print(torch.softmax(k.to(torch.float32), dim=0))
print(torch.relu(k))

tensor([[  -inf, 0.6931, 0.0000],
        [0.6931, 1.9459, 2.1972]])
tensor([[1.0000e+00, 7.3891e+00, 2.7183e+00],
        [7.3891e+00, 1.0966e+03, 8.1031e+03]])
tensor([[0.0000, 0.9093, 0.8415],
        [0.9093, 0.6570, 0.4121]])
tensor([[0.5000, 0.8808, 0.7311],
        [0.8808, 0.9991, 0.9999]])
tensor([[0.0000, 1.4142, 1.0000],
        [1.4142, 2.6458, 3.0000]])
tensor([[1.1920e-01, 6.6929e-03, 3.3535e-04],
        [8.8080e-01, 9.9331e-01, 9.9966e-01]])
tensor([[0, 2, 1],
        [2, 7, 9]])


## Inplace Operations

In [85]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.4847, 0.9436, 0.3904],
        [0.2499, 0.3206, 0.9753]])
tensor([[0.7582, 0.6688, 0.2651],
        [0.2336, 0.5057, 0.5688]])


In [86]:
m + n #new tensor -> occupy some memeory

tensor([[1.2429, 1.6124, 0.6556],
        [0.4835, 0.8263, 1.5441]])

In [87]:
m.add_(n)

tensor([[1.2429, 1.6124, 0.6556],
        [0.4835, 0.8263, 1.5441]])

In [88]:
m

tensor([[1.2429, 1.6124, 0.6556],
        [0.4835, 0.8263, 1.5441]])

In [89]:
n

tensor([[0.7582, 0.6688, 0.2651],
        [0.2336, 0.5057, 0.5688]])

In [91]:
# torch.relu(n) #new tensor
m.relu_()

tensor([[1.2429, 1.6124, 0.6556],
        [0.4835, 0.8263, 1.5441]])

## Copying a Tensor

In [92]:
a = torch.rand(2,3)
a

tensor([[0.0634, 0.8993, 0.2732],
        [0.3397, 0.1879, 0.5534]])

In [93]:
b = a #shallow copy

In [96]:

id(a), id(b)

(139146616562752, 139146616562752)

In [97]:
b = a.clone() #deep copy

## Tensors Operations on GPU

In [4]:
import torch
torch.cuda.is_available()

True

In [5]:
device = torch.device('cuda')
device

device(type='cuda')

In [6]:
#creating a new tensor on GPU (gpu ram -> vram)
torch.rand((2,3), device=device)

tensor([[0.4994, 0.9626, 0.9815],
        [0.2581, 0.6249, 0.4200]], device='cuda:0')

In [7]:
# or move an existing cpu tensor to gpu
a = torch.rand(2,3)
print(a)

tensor([[0.7129, 0.8091, 0.8530],
        [0.2318, 0.5856, 0.3089]])


In [8]:
b = a.to(device)

In [9]:
b + 5 # on gpu

tensor([[5.7129, 5.8091, 5.8530],
        [5.2318, 5.5856, 5.3089]], device='cuda:0')

In [11]:
# compare gpu and cpu time
import torch
import time

size = 10000

matrix_cpu1 = torch.rand(size, size)
matrix_cpu2 = torch.rand(size, size)

matrix_gpu1 = matrix_cpu1.to(device)
matrix_gpu2 = matrix_cpu2.to(device)

start = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2)
end = time.time()
print("cpu time: ", end-start)

start = time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2)
end = time.time()
print("gpu time: ", end-start)

cpu time:  18.772380590438843
gpu time:  0.0009431838989257812


## Reshape

In [12]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [13]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [14]:
#flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
b = torch.rand(2,3,4)
b

tensor([[[0.8417, 0.0145, 0.7438, 0.3833],
         [0.1867, 0.6740, 0.7573, 0.1333],
         [0.0866, 0.0380, 0.3066, 0.0560]],

        [[0.6114, 0.8814, 0.7089, 0.0157],
         [0.6887, 0.7429, 0.1850, 0.6774],
         [0.8377, 0.3606, 0.7428, 0.9279]]])

In [20]:
# permute -> change shape

c = b.permute(2,1,0)

In [22]:
print(c.shape)
c

torch.Size([4, 3, 2])


tensor([[[0.8417, 0.6114],
         [0.1867, 0.6887],
         [0.0866, 0.8377]],

        [[0.0145, 0.8814],
         [0.6740, 0.7429],
         [0.0380, 0.3606]],

        [[0.7438, 0.7089],
         [0.7573, 0.1850],
         [0.3066, 0.7428]],

        [[0.3833, 0.0157],
         [0.1333, 0.6774],
         [0.0560, 0.9279]]])

In [24]:
#unsqueeze
c = torch.rand(226,226,3)
c.unsqueeze(0).shape, c.unsqueeze(1).shape

(torch.Size([1, 226, 226, 3]), torch.Size([226, 1, 226, 3]))

In [30]:
#squeeze
d = torch.rand(1,20)
d

tensor([[0.8700, 0.6850, 0.1850, 0.8853, 0.6559, 0.7003, 0.3856, 0.8298, 0.1598,
         0.9124, 0.4232, 0.3415, 0.3201, 0.2745, 0.7920, 0.2035, 0.5690, 0.6858,
         0.1569, 0.4129]])

In [34]:
d.squeeze(0)

tensor([0.8700, 0.6850, 0.1850, 0.8853, 0.6559, 0.7003, 0.3856, 0.8298, 0.1598,
        0.9124, 0.4232, 0.3415, 0.3201, 0.2745, 0.7920, 0.2035, 0.5690, 0.6858,
        0.1569, 0.4129])

## Numpy and PyTorch

In [35]:
import numpy as np

In [38]:
a = torch.tensor([1,2,3])
a, type(a)

(tensor([1, 2, 3]), torch.Tensor)

In [39]:
b = a.numpy()
b, type(b)

(array([1, 2, 3]), numpy.ndarray)

In [40]:
c = np.array([1,2,3])
c, type(c)

(array([1, 2, 3]), numpy.ndarray)

In [41]:
torch.from_numpy(c)

tensor([1, 2, 3])