In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN


In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)

In [5]:
df.shape

(569, 31)

In [6]:
#train-test-split

X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size=0.2)

In [7]:
#scaling
scalar = StandardScaler()
X_train = scalar.fit_transform(X_train)
X_test = scalar.transform(X_test)

In [8]:
X_train

array([[-0.51731658, -1.57828533, -0.54551223, ..., -0.32233994,
        -0.12855876, -0.88316706],
       [ 1.21132578,  0.27530384,  1.2104232 , ...,  0.54230699,
         0.25806355, -0.30146893],
       [-0.47980013, -0.668465  , -0.37808096, ...,  0.28786543,
         0.50381134,  1.01800569],
       ...,
       [ 0.23301233, -1.00342373,  0.19118535, ..., -0.00746851,
        -0.34613163, -0.08306578],
       [ 0.38884987,  1.03801391,  0.49884031, ...,  1.53129708,
         0.16258193,  1.19379359],
       [ 1.41045153, -0.10265634,  1.31925352, ...,  0.10006334,
        -0.10664494, -1.0056859 ]])

In [9]:
y_train

,diagnosis
170,B
516,M
485,B
466,B
281,B
...,...
536,M
91,M
472,B
509,M


In [10]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [11]:
y_train

array([0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1,

## Numpy Array to Pytorch Tensor

In [12]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [13]:
X_train_tensor.shape

torch.Size([455, 30])

In [14]:
y_train_tensor.shape

torch.Size([455])

## Define the model

In [15]:
import torch.nn as nn
class MySimpleNN(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features,1),
        nn.Sigmoid()
    )

    # self.weights = torch.rand(X.shape[1],1, dtype=torch.float64, requires_grad=True)
    # self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    out = self.network(X)
    return out
    # z = torch.matmul(X, self.weights) + self.bias
    # y_pred = torch.sigmoid(z)
    # return y_pred

  def loss_function(self, y_pred, y):
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)
    return -(y*torch.log(y_pred) + (1-y)*torch.log(1-y_pred)).mean()


## important parameters

In [16]:
learning_rate = 0.1
epochs = 25

## Training Pipeline

In [18]:
model = MySimpleNN(X_train_tensor.shape[1])
model = model.double() # Cast model parameters to float64
# model.weights, model.bias
# print(model.weights.shape)
# print(model.bias.shape)

#Define loop
for epoch in range(100):
  #forward pass
  y_pred = model(X_train_tensor)
  # y_pred = model.forward(X_train_tensor)
  # print(y_pred)

  #loss cal
  loss = model.loss_function(y_pred, y_train_tensor.double()) # Cast y_train_tensor to float64 for compatibility
  # print(loss)


  #backward
  loss.backward()

  #update params
  with torch.no_grad():
    for param in model.parameters():
      param -= learning_rate * param.grad
    # model.weights -= learning_rate * model.weights.grad
    # model.bias -= learning_rate * model.bias.grad

  #zero grad
  for param in model.parameters():
    param.grad.zero_()
  # model.weights.grad.zero_()
  # model.bias.grad.zero_()

  print(f'Epoch : {epoch+1}, Loss: {loss.item()}')

Epoch : 1, Loss: 0.8136446200750063
Epoch : 2, Loss: 0.770987838930243
Epoch : 3, Loss: 0.7452534049607905
Epoch : 4, Loss: 0.7303372102628063
Epoch : 5, Loss: 0.7215646809464916
Epoch : 6, Loss: 0.7160311628803575
Epoch : 7, Loss: 0.7121616461683079
Epoch : 8, Loss: 0.7091642959095815
Epoch : 9, Loss: 0.706653535621629
Epoch : 10, Loss: 0.704441914864189
Epoch : 11, Loss: 0.7024361246578825
Epoch : 12, Loss: 0.7005873237375241
Epoch : 13, Loss: 0.6988678517250927
Epoch : 14, Loss: 0.6972603739301867
Epoch : 15, Loss: 0.695752806405531
Epoch : 16, Loss: 0.6943359161020521
Epoch : 17, Loss: 0.6930021599035484
Epoch : 18, Loss: 0.6917451008041223
Epoch : 19, Loss: 0.6905590964655633
Epoch : 20, Loss: 0.6894391193799119
Epoch : 21, Loss: 0.6883806431125203
Epoch : 22, Loss: 0.6873795636725829
Epoch : 23, Loss: 0.6864321410117378
Epoch : 24, Loss: 0.6855349530834366
Epoch : 25, Loss: 0.6846848584183377
Epoch : 26, Loss: 0.6838789648890427
Epoch : 27, Loss: 0.6831146032128198
Epoch : 28, Lo

In [20]:
for params in model.parameters():
  print(params)

Parameter containing:
tensor([[-0.0444, -0.1062, -0.0009, -0.0242, -0.0359, -0.1099,  0.2005, -0.1049,
         -0.0219,  0.0649, -0.0132,  0.0027,  0.1465, -0.1383, -0.1096, -0.0383,
         -0.1234,  0.1178,  0.0570,  0.0602,  0.0173,  0.1028,  0.0818,  0.0003,
          0.0971,  0.1422, -0.0890, -0.0290, -0.0632, -0.1004]],
       dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([-0.4171], dtype=torch.float64, requires_grad=True)


In [23]:
for idx, layer in enumerate(model.network):
  print(f"Layer {idx+1}: {layer}")

  if hasattr(layer, 'weight'):
    print(f"Weights: {layer.weight}")
  if hasattr(layer, 'bias'):
    print(f"Bias: {layer.bias}")

  print("="*40)

Layer 1: Linear(in_features=30, out_features=1, bias=True)
Weights: Parameter containing:
tensor([[-0.0444, -0.1062, -0.0009, -0.0242, -0.0359, -0.1099,  0.2005, -0.1049,
         -0.0219,  0.0649, -0.0132,  0.0027,  0.1465, -0.1383, -0.1096, -0.0383,
         -0.1234,  0.1178,  0.0570,  0.0602,  0.0173,  0.1028,  0.0818,  0.0003,
          0.0971,  0.1422, -0.0890, -0.0290, -0.0632, -0.1004]],
       dtype=torch.float64, requires_grad=True)
Bias: Parameter containing:
tensor([-0.4171], dtype=torch.float64, requires_grad=True)
Layer 2: Sigmoid()


## Evaluation

In [25]:
with torch.no_grad():
  y_pred = model(X_test_tensor)
  # y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()

  accuracy = (y_pred==y_test_tensor).float().mean()

print(f"Accuracy : {accuracy.item()}")
# print(y_pred, y_train_tensor)

Accuracy : 0.6723607182502747


# Using Linear Layer instead Of Sequential + builtIn gradient + builtIn loss fun

In [27]:
class MySimpleNN(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, X):
    out = self.linear(X)
    out = self.sigmoid(out)
    return out

  # def loss_function(self, y_pred, y):
  #   epsilon = 1e-7
  #   y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)
  #   return -(y*torch.log(y_pred) + (1-y)*torch.log(1-y_pred)).mean()

  def accuracy(self, y_pred, y):
    y_pred = (y_pred > 0.5).float()
    accuracy = (y_pred==y).float().mean()
    return accuracy

In [31]:
learning_rate = 0.1
epochs = 25

In [33]:
loss_function = nn.BCELoss()
# type(loss_function)

In [39]:
model = MySimpleNN(X_train_tensor.shape[1]).double()

optimizer = torch.optim.SGD(model.parameters(),lr=learning_rate)

#Define loop
for epoch in range(100):
  #forward pass
  y_pred = model(X_train_tensor)

  #loss cal
  # loss = model.loss_function(y_pred, y_train_tensor)
  loss = loss_function(y_pred, y_train_tensor.view(-1,1).double())

  #zero grad (new)
  optimizer.zero_grad()

  #backward
  loss.backward()

  #update params
  # with torch.no_grad():
  #   model.linear.weight -= learning_rate * model.linear.weight.grad
  #   model.linear.bias -= learning_rate * model.linear.bias.grad

  optimizer.step()

  #zero grad
  #do befoe backward
  # model.linear.weight.grad.zero_()
  # model.linear.bias.grad.zero_()

  print(f'Epoch : {epoch+1}, Loss: {loss.item()}')

Epoch : 1, Loss: 0.845485999385895
Epoch : 2, Loss: 0.605795377054797
Epoch : 3, Loss: 0.48522086545248083
Epoch : 4, Loss: 0.4162935270196905
Epoch : 5, Loss: 0.37133262937312395
Epoch : 6, Loss: 0.33926595122132663
Epoch : 7, Loss: 0.31496402230786635
Epoch : 8, Loss: 0.29573123959838515
Epoch : 9, Loss: 0.28001168822235345
Epoch : 10, Loss: 0.26684143455514053
Epoch : 11, Loss: 0.25558948887990157
Epoch : 12, Loss: 0.24582419227328567
Epoch : 13, Loss: 0.23723938890083
Epoch : 14, Loss: 0.2296112902692769
Epoch : 15, Loss: 0.22277207893978834
Epoch : 16, Loss: 0.21659311344288096
Epoch : 17, Loss: 0.2109738798596181
Epoch : 18, Loss: 0.2058345112259303
Epoch : 19, Loss: 0.20111059369307213
Epoch : 20, Loss: 0.19674947995996653
Epoch : 21, Loss: 0.19270762113445708
Epoch : 22, Loss: 0.18894860208063952
Epoch : 23, Loss: 0.18544167236700676
Epoch : 24, Loss: 0.18216063254709933
Epoch : 25, Loss: 0.17908297921771738
Epoch : 26, Loss: 0.17618924117317147
Epoch : 27, Loss: 0.173462458430

In [38]:
with torch.no_grad():
  y_pred = model(X_test_tensor)
  y_pred = (y_pred > 0.5).float()

  accuracy = (y_pred==y_test_tensor).float().mean()

print(f"Accuracy : {accuracy.item()}")
# print(y_pred, y_train_tensor)

Accuracy : 0.5584795475006104
