In [6]:
import torch
import torch.nn as nn

class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out




In [7]:
features = torch.rand(10,5)
model = Model(features.shape[1])
model(features)

tensor([[0.5771],
        [0.5142],
        [0.5208],
        [0.5208],
        [0.4965],
        [0.5489],
        [0.5851],
        [0.5183],
        [0.5315],
        [0.5861]], grad_fn=<SigmoidBackward0>)

In [9]:
model.linear.weight, model.linear.bias

(Parameter containing:
 tensor([[-0.2898,  0.0389,  0.1456,  0.3008,  0.0984]], requires_grad=True),
 Parameter containing:
 tensor([-0.0008], requires_grad=True))

In [10]:
!pip install torchinfo

In [12]:
from torchinfo import summary
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [13]:
## Improved Code -> 5 input layer, 3 in hidden layer, 1 in output layer

In [14]:
class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear1 = nn.Linear(num_features, 3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)
    return out

In [15]:
features = torch.rand(10,5)
model = Model(features.shape[1])
model(features)

tensor([[0.4776],
        [0.4750],
        [0.4753],
        [0.4610],
        [0.4455],
        [0.4597],
        [0.4875],
        [0.4793],
        [0.4687],
        [0.4600]], grad_fn=<SigmoidBackward0>)

In [16]:
model.linear1.weight, model.linear1.bias, model.linear2.weight, model.linear2.bias

(Parameter containing:
 tensor([[-0.2513,  0.2947,  0.4371, -0.0103,  0.4000],
         [ 0.2359, -0.2994, -0.3368,  0.3086, -0.3024],
         [-0.0668, -0.0599,  0.2149,  0.1256, -0.0586]], requires_grad=True),
 Parameter containing:
 tensor([ 0.0397, -0.1980,  0.3084], requires_grad=True),
 Parameter containing:
 tensor([[-0.2552, -0.4601, -0.0350]], requires_grad=True),
 Parameter containing:
 tensor([-0.0015], requires_grad=True))

In [18]:
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

## Sequential Conatiner : will help us not to write too many lines of code in forward pass

In [23]:
class SequentialModel(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features,3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
    )

  def forward(self, features):
    out = self.network(features)
    return out

In [24]:
features = torch.rand(10,5)
model = SequentialModel(features.shape[1])
model(features)

tensor([[0.6186],
        [0.6219],
        [0.6315],
        [0.6316],
        [0.6371],
        [0.6174],
        [0.6315],
        [0.6315],
        [0.6259],
        [0.6245]], grad_fn=<SigmoidBackward0>)

In [26]:
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
SequentialModel                          [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [28]:
for param in model.parameters():
    print(param)

Parameter containing:
tensor([[ 0.3777, -0.1914, -0.1989, -0.3844,  0.3540],
        [-0.0496,  0.3285, -0.0137, -0.0012,  0.2783],
        [-0.2888, -0.4414,  0.0390,  0.2083,  0.1268]], requires_grad=True)
Parameter containing:
tensor([ 0.3141, -0.2564,  0.1742], requires_grad=True)
Parameter containing:
tensor([[-0.0078, -0.2442,  0.1261]], requires_grad=True)
Parameter containing:
tensor([0.5390], requires_grad=True)


In [29]:
for name, param in model.named_parameters():
    print(name, param)

network.0.weight Parameter containing:
tensor([[ 0.3777, -0.1914, -0.1989, -0.3844,  0.3540],
        [-0.0496,  0.3285, -0.0137, -0.0012,  0.2783],
        [-0.2888, -0.4414,  0.0390,  0.2083,  0.1268]], requires_grad=True)
network.0.bias Parameter containing:
tensor([ 0.3141, -0.2564,  0.1742], requires_grad=True)
network.2.weight Parameter containing:
tensor([[-0.0078, -0.2442,  0.1261]], requires_grad=True)
network.2.bias Parameter containing:
tensor([0.5390], requires_grad=True)


In [30]:
for idx, layer in enumerate(model.network):
    print(f"Layer {idx}: {layer}")

    if hasattr(layer, "weight"):
        print("Weight:")
        print(layer.weight)

    if hasattr(layer, "bias"):
        print("Bias:")
        print(layer.bias)

    print("-" * 40)

Layer 0: Linear(in_features=5, out_features=3, bias=True)
Weight:
Parameter containing:
tensor([[ 0.3777, -0.1914, -0.1989, -0.3844,  0.3540],
        [-0.0496,  0.3285, -0.0137, -0.0012,  0.2783],
        [-0.2888, -0.4414,  0.0390,  0.2083,  0.1268]], requires_grad=True)
Bias:
Parameter containing:
tensor([ 0.3141, -0.2564,  0.1742], requires_grad=True)
----------------------------------------
Layer 1: ReLU()
----------------------------------------
Layer 2: Linear(in_features=3, out_features=1, bias=True)
Weight:
Parameter containing:
tensor([[-0.0078, -0.2442,  0.1261]], requires_grad=True)
Bias:
Parameter containing:
tensor([0.5390], requires_grad=True)
----------------------------------------
Layer 3: Sigmoid()
----------------------------------------
